Pattern factory
artsiom-kotau/anton-stock-feed pull request #1
Opened 2021-06-22 08:57 UTC by Palshyn46

2021-06-22 09:32 UTC, artsiom-kotau requested changes

2021-06-22 09:32 UTC, artsiom-kotau commented on pom.xml
>          </dependency>
Remove pom.xml
Try to package project with native tools

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataService.java
> +public abstract class DataService {
make interface

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataService.java
> +public abstract class DataService {
CompanyDataService, CompanyProfileService

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataService.java
> +    public abstract JSONObject getInfo();
Company class(model)

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataService.java
> +    public abstract JSONObject getInfo();
getInfo -> getInfo(String companySymbol)

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataServiceFactory.java
> +public abstract class DataServiceFactory {
unnecessary

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataServiceMock.java
> +public class DataServiceMock extends DataService {
rename

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataServiceMock.java
> +            e.printStackTrace();
to Runtime(e) exception

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataServiceMockDatabase.java
> +public class DataServiceMockDatabase extends DataService {
remove

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/DataServiceRealDatabase.java
> +public class DataServiceRealDatabase extends DataService {
remove

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/RealDataServiceFactory.java
> +    public DataService createDataClass(String type) {
rename CompanyService

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +        dataService = realDataServiceFactory.createDataClass("Mock");
init during initialization

2021-06-22 09:32 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +        JSONObject jsonObject = dataService.getInfo();
Serialize here

2021-06-23 10:11 UTC, Palshyn46 commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +        JSONObject jsonObject = dataService.getInfo();
По сериализации вопрос. Вручную или GSON?

2021-06-23 11:15 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +        JSONObject jsonObject = dataService.getInfo();
любая либа

2021-06-23 15:04 UTC, artsiom-kotau requested changes

2021-06-23 15:04 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileService.java
> +    public abstract CompanyClass getInfo(String companySymbol);
public abstract  - в интерфейсах это не нужно

2021-06-23 15:04 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileServiceMock.java
> +    String jsonStringAAPL = "{\"currency\":\"USD\",\"description\":\"APPLE INC\",\"displaySymbol\":\"AAPL\",\"figi\":\"BBG000B9XRY4\",\"mic\":\"XNAS\",\"symbol\":\"AAPL\",\"type\":\"Common Stock\"}";
Remove json, use static objects

2021-06-23 15:04 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +            jsonObject = new JSONObject();
use one-shot serialization

2021-06-24 17:48 UTC, Palshyn46 commented on pom.xml
>          </dependency>
импосибуль)

2021-06-24 20:03 UTC, artsiom-kotau requested changes

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileService.java
> +    CompanyClass getInfo(String companySymbol, CompanyProfileDAO companyProfileDAO);
убрать CompanyProfileDao из параметров. это уже детали имплементации

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileServiceMock.java
> +        this.companyProfileDAO = companyProfileDAO;
инициализация в конструкторе

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/model/CompanyClass.java
> +public class CompanyClass {
переименуй в Company

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +    String jsonString;
начиная от сюда

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +    String companySymbolFromURL;
заканчивая этим местом: почему эти переменные свойства класса, а не метода

2021-06-24 20:03 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +            throw new CompanyProfileException(e);
в случае ошибки ты выставляешь детали имплементации пользователю. Мы с тобой обсуждали как этого избежать

2021-06-24 20:04 UTC, artsiom-kotau commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileDAOMock.java
> +        return companyClass;
а тут ошибки нету, обычно происходит ошибка компиляции, если переменная не инициализирована

2021-06-25 10:28 UTC, Palshyn46 commented on src/main/java/com/example/anton_stock_feed/servlets/CompanyProfile.java
> +    String companySymbolFromURL;
объявлял пораньше, чтобы не мешали менять код)

2021-06-25 10:32 UTC, Palshyn46 commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileDAOMock.java
> +        return companyClass;
ошибки нету. как лучше в таких случаях делать?

2021-06-25 10:41 UTC, Palshyn46 commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileServiceMock.java
> +        this.companyProfileDAO = companyProfileDAO;
что ты имеешь ввиду?

2021-06-25 14:37 UTC, Palshyn46 commented on src/main/java/com/example/anton_stock_feed/classes/CompanyProfileService.java
> +    CompanyClass getInfo(String companySymbol, CompanyProfileDAO companyProfileDAO);
то есть экземпляр companyprofiledao нужно создавать внутри метода getinfo?

2021-06-27 18:31 UTC, artsiom-kotau approved these changes

2021-06-27 18:32 UTC, merged